# Generated by Django 3.2 on 2023-04-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_orderanon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderanon',
            options={'verbose_name_plural': '9.All Orders'},
        ),
        migrations.RemoveField(
            model_name='orderanon',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderanon',
            name='quan',
        ),
        migrations.AddField(
            model_name='orderanon',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderanon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
