# Generated by Django 3.2 on 2023-04-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230430_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanon',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderanon',
            name='phone_number',
        ),
    ]
